# ConfigMap for Inventory Service
apiVersion: v1
kind: ConfigMap
metadata:
  name: inventory-service-config
  namespace: microservices
data:
  SPRING_DATASOURCE_URL: "jdbc:mysql://inventory-db-service:3306/inventory_service"
  SPRING_DATASOURCE_USERNAME: "root"

---
# Secret for Inventory Service
apiVersion: v1
kind: Secret
metadata:
  name: inventory-service-secret
  namespace: microservices
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "Welcome@1234"
  SPRING_DATASOURCE_PASSWORD: "Welcome@1234"

---
# PVC for Inventory Database
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: inventory-mysql-pvc
  namespace: microservices
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard

---
# Inventory Database Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-db
  namespace: microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-db
  template:
    metadata:
      labels:
        app: inventory-db
    spec:
      containers:
      - name: mysql
        image: mysql:9.0
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: inventory-service-secret
              key: MYSQL_ROOT_PASSWORD
        - name: MYSQL_DATABASE
          value: "inventory_service"
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
        - name: init-script
          mountPath: /docker-entrypoint-initdb.d
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          exec:
            command:
            - mysqladmin
            - ping
            - -h
            - localhost
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command:
            - mysqladmin
            - ping
            - -h
            - localhost
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
      volumes:
      - name: mysql-data
        persistentVolumeClaim:
          claimName: inventory-mysql-pvc
      - name: init-script
        configMap:
          name: inventory-db-init
          optional: true

---
# Inventory Database Service
apiVersion: v1
kind: Service
metadata:
  name: inventory-db-service
  namespace: microservices
spec:
  type: ClusterIP
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    app: inventory-db

---
# Inventory Service Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-service
  namespace: microservices
spec:
  replicas: 2
  selector:
    matchLabels:
      app: inventory-service
  template:
    metadata:
      labels:
        app: inventory-service
    spec:
      containers:
      - name: inventory-service
        image: inventory-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8084
        envFrom:
        - configMapRef:
            name: inventory-service-config
        env:
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: inventory-service-secret
              key: SPRING_DATASOURCE_PASSWORD
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8084
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8084
          initialDelaySeconds: 30
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3

---
# Inventory Service
apiVersion: v1
kind: Service
metadata:
  name: inventory-service
  namespace: microservices
spec:
  type: ClusterIP
  ports:
  - port: 8084
    targetPort: 8084
  selector:
    app: inventory-service